### ISSUE TITLE
Listrr TV show lists not pulling through on Python PlexLibrary

### ISSUE THREAD

**Issue by timmehtimtims** [TheUltimateC0der/Listrr#101]
Slightly odd question. I've just started experimenting with this and it's awesome. I use PlexLibrary (https://github.com/adamgot/python-plexlibrary/) to manage dynamic libraries based on trakt lists. However, I can't seem to get any of the TV show lists that I create with listrr to pull data through data from Trakt. I get an indication to show that the programme works but it won't pull data through.

Interestingly, if I simply swap out the list for another one that I've created outside of listrr, then it works fine.

Is this a known issue? I can't see how it can because a list is a list is a list... right? But I'm completely at a loss as to what else it can be because the only variable which causes it to fail is links created with listrr :(

```
user@Ubuntu-1804-bionic-64-minimal:/opt/appdata/pydpl$ cd /opt/appdata/pydpl/&& sudo python plexlibrary netflix_tv

Running the recipe 'netflix_tv'

Retrieving the trakt list: https://api.trakt.tv/users/xxxxxxxxxxxx/lists/netflix-tv-shows/items/tv

Trying to match with items from the 'TV Shows' library

Creating symlinks for 0 matching items in the library...

Created symlinks for 0 new items:

Creating the 'Netflix TV Shows' library in Plex...

Library already exists in Plex. Scanning the library...

Waiting for metadata to finish downloading...

Retrieving a list of items from the 'Netflix TV Shows' library in Plex...

Setting the sort titles for the 'Netflix TV Shows' library...

Number of items in the new library: 0

Number of missing items: 0

Done!
```

Any advice would be great. Would love to get this working properly :)

**Comment by TheUltimateC0der** [comment]
Solution: https://www.reddit.com/r/mdblist/comments/ih3rnv/compatibility_with_plexlibrary/
