### ISSUE TITLE
Issue when attempting to delete an older List

### ISSUE THREAD

**Issue by taylorcox75** [TheUltimateC0der/Listrr#103]
`Whoops... error!!?!`
`An error occurred while processing your request.`

`Request ID: |1be877aa-4c06cf15fa8a2f32.`

![Screenshot_20201014-162410](https://user-images.githubusercontent.com/10939863/96055773-cd95bf80-0e39-11eb-9d88-12f02eafceff.png)

Have 5/8 lists total. This occurs for 2 of the "large lists"  

The error code is the same regardless of the list
1be877b4-4c06cf15fa8a2f32

I deleted the lists initially on  trakt and when I went to delete via listrr, that's where the message came up. Also tried to update the query and save which also gives the same error. 

Did it on Android chrome, attempted via mac and firefox with same issue.

**Comment by TheUltimateC0der** [comment]
Write me a PM on discord. I can help you there.
