### ISSUE TITLE
Ability to exclude genres

### ISSUE THREAD

**Issue by M9D4** [TheUltimateC0der/Listrr#11]

**Comment by TheUltimateC0der** [comment]
If you want to exclude genres, select all genres except the ones you don´t want.

**Comment by M9D4** [comment]
That wouldn't work as most shows have multiple genres, so if I select everything except documentaries, I will still get documentaries which have another genre attached to it

**Comment by TheUltimateC0der** [comment]
That is a feature that I cannot provide currently since this is not implemented by the Trakt API. See https://trakt.docs.apiary.io/#introduction/filters

**Comment by M9D4** [comment]
Yeah that's what I feared... too bad!
