### ISSUE TITLE
Allow deleting a list from Listrr without deleting it from Trakt.

### ISSUE THREAD

**Issue by chazlarson** [TheUltimateC0der/Listrr#123]
Perhaps one uses the "name-based list" to set up a static list of things which won't be updated once created [something like some website's list of the 100 best horror movies or the like].

There's no reason for Listrr to keep updating it, but presently one can't delete the list from Listrr without also deleting it from Trakt.

This is an alternative to #124

**Comment by TheUltimateC0der** [comment]
We do not use trakt anymore
