### ISSUE TITLE
Create lists of BrutX (french platform)

### ISSUE THREAD

**Issue by PierreDurrr** [TheUltimateC0der/Listrr#127]
Would like the feature of being able to create lists with all BrutX ([https://www.brutx.com/](https://www.brutx.com/)) shows only in it

**Comment by TheUltimateC0der** [comment]
This is fixed in V2. Come to the discord linked in the readme, and write me a PM to get access to test it out.

**Comment by PierreDurrr** [comment]
Sorry, can't find BrutX in any way. Might be dumb.
