### ISSUE TITLE
Provide a means of reviewing or repairing mismatched items from "list of names" lists

### ISSUE THREAD

**Issue by chazlarson** [TheUltimateC0der/Listrr#129]
If Listrr produces a mismatch when processing a list of titles, the only way to "recover" is to delete the list and try again.  This can be a painful process since it's not always apparent where the mismatch is.  For example, I just created a list based on a Looper list "98 best sci fi movies".  I massaged the web page to get the formatted list, pasted it into LIstrr, and created the list, which ultimately had 98 entries.  I compared them and found three mismatches:

Fast Color (2018)
Matched as: Before 'I Do' 2018
Should have been Fast Color (2019) [year was wrong in the Looper list]

Superman: The Movie (1978)
Matched as: Superman The Movie Restored International Cut (1978)
Should have been Superman (1978) [removing ": The Movie" got the right one]

Under the Skin (2013)
Matched as Under the Skin (2013)
Should have been Under the Skin (2014) [year was wrong in the Looper list]

Of course, none of those are Listrr's fault, the year was wrong or the title was misleading.  However, to address this I have to delete the list, make those changes, then recreate the list and repeat the process.  If something was not matched and just dropped, it can be a pain to figure out which one or ones that happened to; if this list had appeared at Trakt with 96 entries, for example.

I can't make the fixes at Trakt, since Listrr will overwrite them next time it runs [issue #124 would address this problem].  I would like at a minimum to get a "here's what I did" report of some kind from Listrr to tell me what it matched each of my names to [or if it was unable to].  Ideally, I'd be able to modify the list in place [like I can modify the filters of an existing list] and run it again to fix those matches without having to save a copy of the list of names elsewhere and do the delete/recreate thing.

**Comment by TheUltimateC0der** [comment]
This is fixed in V2. Come to the discord linked in the readme, and write me a PM to get access to test it out.
