### ISSUE TITLE
Donation does not seem to change the interface

### ISSUE THREAD

**Issue by mcrownover** [TheUltimateC0der/Listrr#131]
How do I tie my GitHub account to the Listrr.pro account.  As it is right now no changes have been made to the interface after the GitHub sponsor donation.  According to the banner on top, I should be able to filter by IMDb and have some filters.

 New features!

With a $1 donation, you can now filter by IMDb ratings! We also added a new exclusion filter, to exclude a list of keywords from the movie or show title!

**Comment by TheUltimateC0der** [comment]
@mcrownover You can link your GitHub account by pressing Donating -> Link GitHub Account. 

Its in the menu.

**Comment by TheUltimateC0der** [comment]
It seems that this issue is resolved
