### ISSUE TITLE
Ability to add lists to Listrr.pro via API.

### ISSUE THREAD

**Issue by SaintNick1214** [TheUltimateC0der/Listrr#133]
I'd like to be able to programmatically create filter lists in Listrr.pro through an authenticated api.  This would be neat. :)

**Comment by TheUltimateC0der** [comment]
This is already planned for V2 which I am already working on.

Most likely this will be implemented as a GraphQL API.

**Comment by SaintNick1214** [comment]
Hooray!  Thanks @TheUltimateC0der !

**Comment by TheUltimateC0der** [comment]
Would be nice to discuss this implementation on my discord
