### ISSUE TITLE
[Request] Language Codes

### ISSUE THREAD

**Issue by samsepiol59** [TheUltimateC0der/Listrr#135]
Hey there, I'd like to filter out languages like japanese, chinese, hindi, etc from my lists but I can't really understand which language is which! I noticed there's a closed issue similar to this one, and I assumed the codes where set to latin words! Is this happening to everyone or only me?

Thank you very much!

<img width="655" alt="Screenshot 2022-03-09 at 13 15 34" src="https://user-images.githubusercontent.com/34254280/157440339-9b17c6bd-3bb2-401a-9ee0-0498f6925685.png">

**Comment by TheUltimateC0der** [comment]
This is fixed in V2. Come to the discord linked in the readme, and write me a PM to get access to test it out.
