### ISSUE TITLE
Jellyfin Plugin

### ISSUE THREAD

**Issue by seniorm0ment** [TheUltimateC0der/Listrr#138]
Suggesting Jellyfin plugin

**Comment by TheUltimateC0der** [comment]
Can you explain a bit more what the plugin should actually do?

**Comment by seniorm0ment** [comment]
We have a Plex plugin don't we? same functionality but for Jellyfin

**Comment by TheUltimateC0der** [comment]
I have not developed anything for plex regarding listrr. Can you give a link to the plugin?

**Comment by seniorm0ment** [comment]
Python-PlexLibrary is listed on the Listrr readme. Unless I'm mistaken as to what exactly it is?

You can create libraries from your the trakt lists you created with Listrr. As your lists get updated every 24 hours, so does your libraries.

**Comment by TheUltimateC0der** [comment]
Okay. But the Python-PlexLibrary project is not from me. You can contact the developer to ask him if he is interested into creating the same for Jellyfin

**Comment by seniorm0ment** [comment]
Ah ok
