### ISSUE TITLE
TV Shows Extensive filtering not filtering Genre's correctly

### ISSUE THREAD

**Issue by yhs4260** [TheUltimateC0der/Listrr#141]
I am creating a new Extensive filtering and attempting to exclude certain Genre's.

Issue 1 -  The Genre's - Name dropdown lists each Genre multiple times. There are 12 of each Genre, ie - 12 Crime Genre's.

Issue 2 - The Genre's are not being filtered correctly. I have created a list and specifically excluded Genre the "Documentary" genre, however it continues to include them. An included show example is:

"30 Minute Meals" - https://www.themoviedb.org/tv/2123-30-minute-meals

I can only exclude it, by exclusively including only certain named Genre's.

The above issue is also happening for Kids and some other Genre's.

**Comment by TheUltimateC0der** [comment]
>Issue 1 - The Genre's - Name dropdown lists each Genre multiple times. There are 12 of each Genre, ie - 12 Crime Genre's.

This is now fixed. Thx for reporting.

>Issue 2 - The Genre's are not being filtered correctly.

It is filtered correctly. As you can see the series does not have any genre set. So if your filter says you want everything except "Documentary", it will match everything that doesnt have the "Documentary" genre. If a show doesnt have any genre, it will not match your exclusion.

I added the operators `Is not null` and `is null`. So you can set your filter to Not Equal "Documentary" AND Genre Is not null.

Or you go the way you described by exclusively including all genres you want.
