### ISSUE TITLE
Clicking "Logout" displays framework home page

### ISSUE THREAD

**Issue by chazlarson** [TheUltimateC0der/Listrr#18]
I'm logged in; I click "logout" and see this:

![image](https://user-images.githubusercontent.com/3865541/65252018-dfcdee80-dabd-11e9-8303-04a35b5a7682.png)

**Comment by TheUltimateC0der** [comment]
This is correct like it is currently. This is caused by the template used to create listrr application. If you have any Idea what could be there, you can make a suggestion, or change the content of https://github.com/TheUltimateC0der/Listrr/blob/develop/Listrr/Views/Home/Index.cshtml and make a PR
