### ISSUE TITLE
Ability to create RSS from lists and include tvdbid

### ISSUE THREAD

**Issue by maximuskowalski** [TheUltimateC0der/Listrr#30]
Feature request.

**Comment by TheUltimateC0der** [comment]
Can you please add an example URL of how the format looks like ?

**Comment by maximuskowalski** [comment]
`<newznab:attr name="tvdbid" value="316793"/>`
From an nzb indexer RSS

**Comment by maximuskowalski** [comment]
This can then be passed to sonarr to add a show for example.

**Comment by TheUltimateC0der** [comment]
I need either the complete RSS feed output or a URL where I can see what needs to be in the RSS content

**Comment by maximuskowalski** [comment]
`https://api.nzbgeek.info/rss?t=5045&dl=1&num=50&r=xxxxxxxxxxxxx`

But needs an api added to replace XXX for example.

**Comment by TheUltimateC0der** [comment]
Still needed ?
