### ISSUE TITLE
Create lists of Amazon Movies

### ISSUE THREAD

**Issue by chrispy12** [TheUltimateC0der/Listrr#31]
Would like the feature of being able to create lists with all Amazon movies only in it

**Comment by TheUltimateC0der** [comment]
This would require to add another provider like IMDB or TMDB for checking this since the trakt API does not include information about this.

**Comment by Migz93** [comment]
Just want to give my +1 to this feature, would appreciate being able to have a list of movies produced by the main streaming services to go alongside my tv show list. Understand that it probably won't be anytime soon as it'd have to be a whole other API to be integrated.

**Comment by TheUltimateC0der** [comment]
As mentioned on the discord :

> The problem here is that I have to get this information somewhere. Since the Trakt API does not provide this information, I have to get it from the IMDb & RT API. The problem here is, that a single list can contain ten thousands of items, and I guess IMDb and RT will not be happy about the fuckton of API requests this generates, as I have to make one request for each movie/show. This will take some seriuos load on the IMDb/RT servers which I dont want, and I guess they dont want too

> The other possible way would be to save those informations in the listrr database, but this means to have a db with hundreds of thousands of entries and also with tons of constrains and cross references between tables. That means that there has to be some serious processing power to query the information from the database

> With pulling metadata from different sources there would be the benefit of having more precise filters as Imdb, and tmdb are more popular than trakt and give better results for filtering on metadata stuff.
Especially for votings and stuff
Imdb, tmdb, tvdb and rotten would definitely contribute towards more reliable filtering
I mean I already discussed this in the #donors channel. I was thinking about providing a service like omdb that combines all of these sources into one big source
I am having no problem developing such a tool, the bigger problem is funding of such a project

> + having that data in an own database would allow to extend the API step by step in a community driven way. This would lead to the ultimate tool for creating lists and other tools for ppl that use sonarr and radarr.

Until we get some serious funding for this, this is closed. A raw estimate of around 150-200€/month should get us to a point where we consider this.

**Comment by TheUltimateC0der** [comment]
You might already know this, but for the people looking at this issue, and dont already know:

We got enough funding for this, and A LOT more. all the new features are available at https://listrr.pro
