### ISSUE TITLE
Max-items limit for list

### ISSUE THREAD

**Issue by g4m3r7ag** [TheUltimateC0der/Listrr#36]
It would be nice to have an option to configure the max-items on a list to use in conjunction with traktarr for full automation of adding movies and TV shows without getting an endless amount of adds to Sonarr and Radarr. If for example you could set your criteria for shows/movies and then set a max-items of 50, then when traktarr pulls the list it will only show 50 items and if they all already exist in your library then none will be added. I imagine it would have to pull the full list of hundreds/thousands that your criteria returns, sort them by the chosen method and then remove everything after the max-items entry has been met.

**Comment by ItsCinnabar** [comment]
What criteria would it use for deciding which shows to keep? Say you set 50, but is that top 50 of popularity? Rank? Votes? Trakt has a lot of sorting options. Or does this feature need to allow you to pick..?

**Comment by g4m3r7ag** [comment]
Since the option to specify the number of votes is already there it would probably be easiest to sort by votes. I know traktarr lets you choose between votes/rating/release so I suppose presenting with the option on how to sort the list would be best as everyone may want something different, but not sure how difficult that would be.

**Comment by g4m3r7ag** [comment]
I've been using the option for minimum number of votes to limit the size of the lists and that seems to be working rather well.

**Comment by TheUltimateC0der** [comment]
Can this be closed?

We now have the ability to filter by votes #35

**Comment by g4m3r7ag** [comment]
Yea, I've been using the minimum votes and that seems like a pretty happy medium to achieve the goal of not having unlimited sized lists constantly being pushed to sonarr/radarr. Would make sense to close.
