### ISSUE TITLE
Certifications exclusion filter 

### ISSUE THREAD

**Issue by g4m3r7ag** [TheUltimateC0der/listrr#52]
Certifications on movie lists do not appear to be working. They also do not appear to be working as exclusions. 

List:
Genres: animation, family
Years: 2019-2020
Rating: 65-100 with 50 votes
English
United States

I have tried both putting certifications
Parental Guidance Suggested/All Ages

As well as putting an exclusion for
Mature Audiences/Parental Guidance Strongly Suggested/Not Rated

With either the list still includes PG-13 titles such as Batman Hush, Reign of the Superman

**Comment by TheUltimateC0der** [comment]
I am sorry to tell you that due to the feature missing in the lib used for communication with trakt api, regardless what you select there, nothing will happen.

**Comment by g4m3r7ag** [comment]
Should it be removed from the front end then? Is it possible to create a list that would only pull movies for Children's Movies?

**Comment by g4m3r7ag** [comment]
Updated the title to reflect that the exclusion filter for movie certifications is not working. Below list should be excluding PG-13 but Batman: Hush and other PG-13 movies appear in the list. 

![image](https://user-images.githubusercontent.com/46694420/71672686-b8d1ba80-2d44-11ea-8f11-b05058526552.png)

**Comment by g4m3r7ag** [comment]
Changed name again, Certification exclusion filter does not appear to be working for shows or movies.

**Comment by g4m3r7ag** [comment]
Here is a movies list that should only include kids movies but contains PG-13
https://listrr.pro/Home/EditMovieList/10741211
https://trakt.tv/users/g4m3r7ag/lists/childrens-movies-2019

Here is a shows list that should NOT contain any kids shows but does
https://listrr.pro/Home/EditShowList/10774577
https://trakt.tv/users/g4m3r7ag/lists/animation-2019

**Comment by markwhat1** [comment]
Just wanted to add that I’m having the same issue.

**Comment by TheUltimateC0der** [comment]
This has been fixed. Take a look here: https://listrr.pro
