### ISSUE TITLE
Github Link does not work

### ISSUE THREAD

**Issue by maximuskowalski** [TheUltimateC0der/Listrr#57]
When trying to link to github account link fails.

`http://localhost:9496/signin-github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-ap`

**Comment by TheUltimateC0der** [comment]
It was late. I entered the wrong ClientId and ClientSecret :P
