### ISSUE TITLE
Run issue - no database found

### ISSUE THREAD

**Issue by jhdscript** [TheUltimateC0der/Listrr#64]
Hi friend i trying to run it, source code compilation is OK but when i try to run it in DEBUG mode i have some database errors.

I don't find any .sql or database info in the code. Coul you help me ? Help will be appreciated because i love your project.

Thanx for the development and have a good time. Regards from FRANCE

**Comment by TheUltimateC0der** [comment]
Hi!

Thank you for your kind words! Really appreciate it :)

Listrr is, and never was intended for selfhosting. Listrr is open source only to audit the source code, to look what data is processed for what purpose.

I wont give any support for selfhosting, and I also wont give any documentation for selfhosting.

Listrr is developed community driven. That means that I implement features, and fix bugs that get reported through the community of Listrr. Listrr is a project I develop in my free time. This project is my experiment if, and how long a community is willing to keep a project alive through donating either time by contributing code, or by donating money to cover the server costs.

You can see https://discordapp.com/channels/632546249819553812/632546249819553814/668788360265072640 or https://discordapp.com/channels/632546249819553812/632546249819553814/668145707051647024 for further explanations.
