### ISSUE TITLE
List Forking

### ISSUE THREAD

**Issue by owine** [TheUltimateC0der/listrr#78]
Would love the ability to to "fork" a list and essentially duplicate the filters of an existing list into your own and then make further tweaks on top of it.

i.e. you find a list of comedy movies, but only want ones in a certain year range and with a certain rating (or remove mature-rated items)

**Comment by owine** [comment]
Somewhat similar, but the ability to filter an existing Trakt list would be cool (not necessarily a Listrr list)

**Comment by TheUltimateC0der** [comment]
> Somewhat similar, but the ability to filter an existing Trakt list would be cool (not necessarily a Listrr list)

Please create a new feature request for this, as this is something complete different from the initial issue.

**Comment by TheUltimateC0der** [comment]
This is now available. Take a look here: https://listrr.pro
