### ISSUE TITLE
Filter with Rotten Tomatoes, IMDB ratings

### ISSUE THREAD

**Issue by Mushin** [TheUltimateC0der/Listrr#88]
It would be great if this could be added. There is no currently no automated solution for this.

**Comment by TheUltimateC0der** [comment]
Please read my comment on this issue here for explanation https://github.com/TheUltimateC0der/Listrr/issues/31#issuecomment-589653560

**Comment by linaspurinis** [comment]
You could use https://mdblist.com which already provide the ability to filter by IMDb, Trakt, TMDb, Letterboxd, Tomatoes, Audience, Metacritics rating, and votes.
