### ISSUE TITLE
Ability to upload CSV/Excel Sheet to create Trakt lists

### ISSUE THREAD

**Issue by morganzero** [TheUltimateC0der/Listrr#89]
Hi, I would love to see a way to create trakt lists in your awesome tool by uploading a CSV file or an Excel sheet.

I currently have 15K movie titles and 5K TV titles, and this feature would mean that I simply would upload my CSV and Listrr would match the titles towards Trakt. Maybe a duplicate detection or a mismatch detection ability is needed for this to really work painlessly.

Either way, thanks for this amazing tool, and I would love to see this as a free or donor feature in Listrr.pro.

**Comment by TheUltimateC0der** [comment]
Genral implementation is done and PR is submitted (https://github.com/TheUltimateC0der/Listrr/pull/91) I will have to test some things, and then I can merge this.

**Comment by TheUltimateC0der** [comment]
Done
